# Generated by Django 4.2.7 on 2023-12-01 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_rename_tag_notation_tag_notion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='user2',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='user1',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='created_at',
        ),
    ]
